networkmap:main
	g++ main.o apartment_method.o -o networkmap -std=c++11
main:apartment_method
	g++ -c main.cpp -o main.o -std=c++11
apartment_method:
	g++ -c apartment_method.cpp -o apartment_method.o -std=c++11